### ISSUE TITLE
Error when warming Linux WebApp

### ISSUE THREAD

**Issue by RicardoGaefke** [luuksommers/vsts-website-warmup#10]
Hi.

Thank you very much for your component. It is really useful but it is not working for me. I have a DevOps project that builds and releases several Linux WebApps and this is the error message:

##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.

Can you please help me?

This is the DevOps project (the release task) >> [https://dev.azure.com/ricardogaefke/Profile4D/_releaseDefinition?definitionId=4&_a=definition-tasks&environmentId=4](https://dev.azure.com/ricardogaefke/Profile4D/_releaseDefinition?definitionId=4&_a=definition-tasks&environmentId=4)

Thank you very much.

**Comment by luuksommers** [comment]
This extension is indeed using powershell for windows, do you know if it is
possible to use powershell core on your deploy agent? That would be a
migration worth investigating.

**Comment by RicardoGaefke** [comment]
Got it. As I am publishing WebApp on a Linux host, I don't think it'll be possible to run Windows PS. Thank you very much anyway. It is a very good tool and it'll be awesome if possible to run on Linux as well.

**Comment by rafalkasa** [comment]
@luuksommers  maybe could you add support for your Extension for linux Azure DevOps agents by use

PowerShell on Linux systems, including Ubuntu… To install, run the commands below install Snap…

```
sudo apt update
sudo apt install snapd
```
Then run the commands below to get PowerShell installed via Snap..

`sudo snap install powershell --classic`

After installing, you can go to the Activities Overview board and search for PowerShell to launch it.. When it opens you should see a message similar to the one below:

```
PowerShell 6.1.1
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.
```
