### ISSUE TITLE
Task description phrasing

### ISSUE THREAD

**Issue by MelGrubb** [luuksommers/vsts-website-warmup#16]
"This task warms-up an webapp by calling it's url"
should be
"This task warms up a webapp by calling its url"

"warms-up" should be two words, "an" should be "a", and the possessive "its" has no apostrophe in it, similar to how "his" and "hers" have no apostrophe. Nitpicky, I know, but since I end up staring at this message for long periods during a deployment with long-running migrations, it irritates me more than most people.

**Comment by luuksommers** [comment]
You are always welcome to submit a pull request. I'm happy to accept
changes like these and release a new version!

**Comment by luuksommers** [comment]
Version 1.1.1 is published to the market place! Thanks for reporting and submitting the PR!
