### ISSUE TITLE
Azure Web App HTTPS

### ISSUE THREAD

**Issue by simader** [luuksommers/vsts-website-warmup#2]
Hello, 

If I want to warmup may azure web app i get the following error:
We have turned on HTTPS Only and minimum TLS Version is 1.2

  | System.Management.Automation.CmdletInvocationException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
-- | --

![grafik](https://user-images.githubusercontent.com/34918640/41145421-54f7cf48-6b00-11e8-9455-3f617a84e695.png)

**Comment by luuksommers** [comment]
Hi simader, thank you for reporting this issue. I will have a look this week. Maybe in the meantime, you can use the option "Ignore SSL errors"?

**Comment by luuksommers** [comment]
The new version has been published to the marketplace, please let me know if it's fixed.
