### ISSUE TITLE
Feature: Basic Authentication

### ISSUE THREAD

**Issue by nkovacic** [luuksommers/vsts-website-warmup#3]
We have a development web app secured with basic authentication and now all warm up request are failing with 401. Would it be possible to add a feature which would enable specifying the username and password for the warm up request?

**Comment by luuksommers** [comment]
If you want, you can submit a pull request yourself, I will be on vacation the next 2 weeks, after that I can add this feature.

**Comment by skalinets** [comment]
@nkovacic it might me easier for you to add some endpoint accessible for anonymous users. You might have it already (eg. login / register pages)

**Comment by nkovacic** [comment]
Unfortunately the basic authentication in this case is used on the whole page, which is still under development and cannot be open to public yet. I other cases i agree that this would be an good workaround.

**Comment by luuksommers** [comment]
I've added the feature, will publish it tomorrow to the store

**Comment by luuksommers** [comment]
Having some issues with the publish, but I'm working on it with the help from Microsoft.

**Comment by luuksommers** [comment]
I've requested a new publisher profile, the new extension will be called vsts-website-warmup (same code, different name) This will probably be confirmed on monday

**Comment by luuksommers** [comment]
https://marketplace.visualstudio.com/items?itemName=luuksommers.website-warmup
