### ISSUE TITLE
VSTS task fails due to webapp-warmup.ps1 reference

### ISSUE THREAD

**Issue by AndyMDoyle** [luuksommers/vsts-website-warmup#4]
Running your newer website-warmup task currently fails with the following error:

The term '.\webapp-warmup.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program.

I beleive it is down to the following line trying to call the original webapp-warmup.ps1 file instead of the newly renamed website-warmup.ps1 script.

https://github.com/luuksommers/vsts-website-warmup/blob/b50e9642ad0e23df2ef1e710fa9ff26497f82cff/website-warmup/run-vsts.ps1#L10

**Comment by luuksommers** [comment]
Thank you so much for reporting this issue, a new version has just been published ! Please let me know if this resolves the issue!

**Comment by AndyMDoyle** [comment]
It's got further than before, but now throws this error:

Cannot process argument transformation on parameter 'basicAuthPassword'. Cannot convert the "" value of type "System.String" to type "System.Security.SecureString".

**Comment by luuksommers** [comment]
I wasn't able to update our own pipeline to use the new variant.. I'm running it now to verify. Sorry for the inconvenience. I'll send and update when it's fixed.

**Comment by AndyMDoyle** [comment]
No trouble at all - found your old version so can use that for now.
Happy to help iron out any niggles though.

**Comment by luuksommers** [comment]
I finally got time to create a test pipeline, so now all should work fine. :)

**Comment by AndyMDoyle** [comment]
Everything looks great now. Thanks for the really quick responses. :)
