### ISSUE TITLE
Warming up pages behind authentication?

### ISSUE THREAD

**Issue by sheam** [luuksommers/vsts-website-warmup#5]
Most of my webapp is only accessible once you have logged int. Will this tool support an authentication, or manaully setting of a cookie or header?

**Comment by luuksommers** [comment]
We now support only basic authentication, I'm always open for pull requests
:) What kind of authentication are you looking for?

**Comment by jabteles** [comment]
@luuksommers Hi, the Authentication version is not yet at Marketplace to download, how can I add this to my TFS? Regards

**Comment by luuksommers** [comment]
The extension has a new variant, it's called website warmup now. It's under
the publisher luuksommers (instead of infocaster).

**Comment by luuksommers** [comment]
Did you find it?

**Comment by jabteles** [comment]
Yes and it worked pretty well!

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________
