### ISSUE TITLE
This Git seems oudated?

### ISSUE THREAD

**Issue by elgorro** [luuksommers/vsts-website-warmup#7]
On [Azure DevOps Marketplace site](https://marketplace.visualstudio.com/items?itemName=luuksommers.website-warmup#overview) it says Version 0.3.8 but in this repo it's 0.3.7, also the last commit here doesn't match the day of update on the marketplace.
Can you merge your code please?

**Comment by luuksommers** [comment]
Forgot to push **SHAME**
